MapSchool/urls.py
# Toutes les URLS de mes applis devront etre declarer ici
# Pour cela je dois importer les urls 
from django.conf.urls import url, include
from django.contrib import admin

# chargement du fichier settings et static pour avoir acces aux fichiers static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Je declare les URL de geolocate
    # le include permettra d'aller chercher dans le dossier correspondant
    # geolocate.urls va recuperer le contenu du fichiers urls.py
    url(r'^geolocate/', include('geolocate.urls', namespace='geolocate')),

]

# Cette strucuture de control me permettra de pointer aisemevt sur les 
#fichiers static correspondant
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

geolocate/urls.py
# Ici fichier de routage de geolocate pas du projet MapSchool
# lors de la creation d'une application django ne cree pas ce fichier 
# donc c'est au programmeur de le faire y compris tous les autres fichiers 
# tel ke serializers.py, forms.py, filters.py ....etc.

from django.conf.urls import url, include
from django.contrib import admin

# Importation des fichiers views.py models.py et serializers.py
from geolocate import views
from geolocate import models
from geolocate import serializers

#definition d'un namespace(petit nom de mon application)
app_name = 'geolocate'


urlpatterns = [
	
	# Chargement des urls du site d'administration depuis mon appli geolocate
	url(r'^admin/', admin.site.urls),

	# Les routes de mon API
	# Pour mieux comprendre la syntaxe des urls, il faut savoir ke la partie de gauche 
	# Affichera l'url ke l'utilisateur verra sur son navigateur
	# La partie du milieu indik la vue de traitement correspondant dans le fichier views.py
	# lapartie de droite s'il yen a indik juste le nom ke l'on a choisit de donner 
	# a notre url afin ke l'on puisse pouvoir pointer dessus comme avec un lien
	# Exemple: <a href="{% url 'geolocate:admin' %}">Aller à la page d'amin</a>
	# Cette route affichera la liste des ets
	url(r'^api/liste/etablissement/$', views.EtablissementList.as_view()),
	# ?P<pk>\d+) cet expression reguliere pemret d'afficher l'identifiant correspodant
	# Exemple: api/ets/1/ ou api/ets/101
	# La route suivante affichera les details d'un ets
    url(r'^api/etablissement/(?P<pk>\d+)/$', views.EtablissementDetailList.as_view()),

	# Les routes de mon site
	url(r'^$', views.EtablissementListView.as_view(), 
		name='etablissement_list'),
    url(r'^etablissement_detail/(?P<pk>\d+)/$', views.EtablissementDetailView.as_view(), 
    	name='etablissement-detail'),
 





]

geolocate/models.py
from django.db import models

# Create your models here.


class Etablissement(models.Model):
	nom = models.CharField(max_length=255, null=True, blank=True, verbose_name="Nom de l'Etablissement")
	ville = models.CharField(max_length=255, null=True, verbose_name="Ville")
	quartier = models.CharField(max_length=255, verbose_name="Nom du Quartier")
	repere = models.TextField(max_length=255, verbose_name="Répère")
	telephone = models.CharField(max_length=30, verbose_name="Telephone(s)")
	email = models.EmailField(max_length=255, verbose_name="Email(s)")
	adresse = models.CharField(max_length=255, verbose_name="Adresse")
	latitude = models.CharField(max_length=255, verbose_name="Latitude")
	longitude = models.CharField(max_length=255, verbose_name="Longitude")


	def __str__(self):
		return self.nom


	class Meta:
		verbose_name_plural = "Etablissements"

geolocate/views.py
from django.shortcuts import get_object_or_404, render, redirect, render_to_response
from .models import Etablissement
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView, ListView
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
import re
from .models import Etablissement
from .serializers import EtablissementSerializer
from rest_framework.views import APIView
from django.http import JsonResponse
from django.http import Http404
from rest_framework.response import Response
from rest_framework import status
from django.db.models import Q
from rest_framework import generics, mixins
from rest_framework.decorators import api_view

# Create your views here.

# Serialization
class EtablissementList(mixins.CreateModelMixin, generics.ListAPIView):

	lookup_field = 'pk'
	#queryset = Etablissement.objects.all()
	serializer_class = EtablissementSerializer

	def get_queryset(self):
		qs = Etablissement.objects.all()
		query = self.request.GET.get("q")
		if query is not None:
			qs = qs.filter(Q(nom__contains=query)|Q(ville__contains=query)).distinct()
		return qs

	def post(self, request, *args, **kwargs):
		return self.create(request, *args, **kwargs)



class EtablissementDetailList(generics.RetrieveUpdateDestroyAPIView):

	lookup_field = 'pk'
	#queryset = Etablissement.objects.all()
	serializer_class = EtablissementSerializer

	def get_queryset(self):
		return Etablissement.objects.all() 


# Etablissement CRUD
class EtablissementListView(ListView):
	model = Etablissement


class EtablissementDetailView(DetailView):
	model = Etablissement

	def get_context_data(self, **kwargs):
		context = super(EtablissementDetailView, self).get_context_data(**kwargs)
		return context

geolocate/templates/geolocate/etablissement_detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>APPSCHOOL</title>

    <!-- Bootstrap -->
    <link href="{% static 'appschool/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
     #map_canvas2 {
       width: 100%;
       height: 400px;
       background-color: grey;
     }
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'appschool:index' %}">APPSCHOOL</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'appschool:index' %}">Acceuil</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'appschool:etudiant_create' %}">S'inscrire'</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">A Propos</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>  APPSCHOOL</h1>
        <p>C'est une petite application developpée avec le framework Django permettant juste de géolocaliser des établissements affiliés de l' AUF, puis de permettre aux personnes souhaitant souscrire à une formation aisément de s'inscrire.</p>
        <p>C'est Simple, pratique et convivial!!!</p>
      </div>

      <div class="row">
        <div class="col-lg-5">
          <h2>{{ object.nom }}</h2>
          <p class="text-danger">Bienvenue à l'institut <a>{{object.nom}}</a>, c'est un centre agrée de l'AUF depuis 1995. Nous offrons des formations diverses et variées notamment dans le cadre de la filiation entre l'Etat gabonais et l'AUF. Ceci etant nos diplômes sont reconnues à l'echelle internationale. Le système educatif est le LMD (License, Master, Doctorat)</p>
          <p>C'est une institution de qualité. </p>

          <div id="bodyContent">
          	<p><h5>Ville: <a href="">{{ object.ville }}</a></h5></p>
            <p><h5>Quartier: <a href="">{{ object.quartier }}</a></h5></p>
            <p><h5>Email: <a href="">{{ object.email }}</a></h5></p>
            <p><h5>Téléphone: <a href="">{{ object.telephone }}</a></h5></p>
            <p><h5>Adresse: <a href="">{{ object.adresse_ets }}</a></h5></p>
            <p>
    			    <a class="btn btn-primary" href="{% url 'appschool:formation_list'  %}">
    			      <span class="glyphicon glyphicon-check"></span>
    			      S'inscrire
    			    </a>
    			</p>
            <p><p>
          </div>


        </div>

        

        <div class="col-md-7">
          <div id="map_canvas2"></div>
        </div>
      </div>

      
	<p></p>
	<p></p>

      

    </div> <!-- /container -->

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyrigth@2018. AUF-ATELIER/DJANGO-ANDROID.</p>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'appschool/js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'appschool/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript">

      function initMap() {
        var directionsService = new google.maps.DirectionsService();
        var directionsDisplay = new google.maps.DirectionsRenderer();

        

        var haight = new google.maps.LatLng(37.7699298, -122.4469157);
        var oceanBeach = new google.maps.LatLng(37.7683909618184, -122.51089453697205);
        var mapOptions = {
          zoom: 14,
          center: haight
        }
        var map = new google.maps.Map(document.getElementById('map_canvas2'), mapOptions);
        directionsDisplay.setMap(map);
      }

      function calcRoute() {
        var selectedMode = document.getElementById('mode').value;
        var request = {
            origin: haight,
            destination: oceanBeach,
            // Note that Javascript allows us to access the constant
            // using square brackets and a string value as its
            // "property."
            travelMode: google.maps.TravelMode[selectedMode]
        };
        directionsService.route(request, function(response, status) {
          if (status == 'OK') {
            directionsDisplay.setDirections(response);
          }
        });
      }

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Erreur: La service de géolocation a echoué.' :
                                  'Erreur: Votre navigateur ne supporte pas la geolocation.');
            infoWindow.open(map);
        }

    
  </script>
        <!--Load the API from the specified URL
        * The async attribute allows the browser to render the page while the API loads
        * The key parameter will contain your own API key (which is not needed for this tutorial)
        * The callback parameter executes the initMap() function
        -->
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvBRw5JjebNnwQW6doJSbSJgAgpdgjs2M&callback=initMap">
        </script>


  </body>
</html>

geolocate/templates/geolocate/etablissement_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>geolocate</title>

    <!-- Bootstrap -->
    <link href="{% static 'geolocate/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
     #map_canvas {
       width: 100%;
       height: 700px;
       background-color: grey;
     }
    </style>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="">geolocate</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="">Acceuil</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="">S'inscrire'</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">A Propos</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>  geolocate</h1>
        <p>C'est une petite application developpée avec le framework Django permettant juste de géolocaliser des établissements affiliés de l' AUF, puis de permettre aux personnes souhaitant souscrire à une formation aisément de s'inscrire.</p>
        <p>C'est Simple, pratique et convivial!!!</p>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div id="map_canvas"></div><br><br><br>
        </div>
      </div>

      

      

    </div> <!-- /container --><br><br><br><br><br><br>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyrigth@2018. AUF-ATELIER/DJANGO-ANDROID.</p>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'geolocate/js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'geolocate/js/bootstrap.min.js' %}"></script>
    <script>


        // Initialize and add the map
        function initMap() {



          var locations = [];

          {% for etablissement in object_list %}
                    locations.push({

                        lng: {{ etablissement.longitude }},
                        lat: {{ etablissement.latitude }},
                        id: {{ etablissement.id }},
                        nom: "{{ etablissement.nom }}",
                        ville: "{{etablissement.ville }}",
                        telephone: "{{ etablissement.telephone }}",
                        email: "{{ etablissement.email }}",
                        quartier: "{{ etablissement.quartier }}"

                    });
          {% endfor %}

          var map = new google.maps.Map(document.getElementById('map_canvas'), {
            zoom: 10,
            center: new google.maps.LatLng(0.390100, 9.454400),
            mapTypeId: google.maps.MapTypeId.ROADMAP
          });

          

            

          var infowindow = new google.maps.InfoWindow();

          var marker, i;

          {% for etablissement in object_list %}

            for (i = 0; i < locations.length; i++) { 

              var content = '<div id="content">'+
              '<h1 id="firstHeading" class="firstHeading">'+locations[i].nom+'</h1>'+
              '<div id="bodyContent">'+
              '<h5>Ville: <a href="#">'+locations[i].ville+'</a></h5>'+
              '<h5>Quartier: <a href="#">'+locations[i].quartier+'</a></h5>'+
              '<h5>Email: <a href="#">'+locations[i].email+'</a></h5>'+
              '<h5>Téléphone: <a href="#">'+locations[i].telephone+'</a></h5>'+
              '<p><a href="{% url 'geolocate:etablissement-detail' etablissement.id %}">'+
              'Voir Détails</a> '+
              '...</p>'+
              '</div>'+
              '</div>'; 


              marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i].lat, locations[i].lng),
                map: map
              });

              google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                  infowindow.setContent(content);
                  infowindow.open(map, marker);
                }
              })(marker, i));
            }

          {% endfor %}
        }
      

    </script>
        <!--Load the API from the specified URL
        * The async attribute allows the browser to render the page while the API loads
        * The key parameter will contain your own API key (which is not needed for this tutorial)
        * The callback parameter executes the initMap() function
        -->
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDvBRw5JjebNnwQW6doJSbSJgAgpdgjs2M&callback=initMap">
        </script>
  </body>
</html>